### PR TITLE
Correct docker build PATH to build context location.

### PR DESCRIPTION
**Pull request by pingzhaozz**
Fix the problem that can't find correct context during docker build.

### CODE REVIEW

**Comment by leyao-daily** [comment]
Thanks for you contirbution. Can you explain more about your changes, what issues do you meet when building the image.

**Comment by pingzhaozz** [comment]
The PATH parameter is the build context location, which mostly use same Dockerfile location. So that if the Dockerfile use patch or other files that docker build could find them. Otherwise build will failure can't find the context file. So far the containers only have Dockerfile which doesn't have issue. But when you add new containers the problem will happen.

**Comment by leyao-daily** [comment]
We use the root as the file context, and all the execution in dockerfile should be considered as a relative path based on the root path.

**Comment by pingzhaozz** [comment]
close this PR as it use top directory for context

**Pull request closed without merging**
