### PR TITLE
cnap/core: add model provider to get model info and download model

### PR DESCRIPTION
**Pull request by dongx1x**
- remove model information got from the env
- add model provider abstract class
- add a simple model provider class to get model info and download the model

### CODE REVIEW

**Comment by dongx1x** [comment]
@Hulongyin Needs your help to check the unit test failures.

**Comment by Hulongyin** [comment]
> @Hulongyin Needs your help to check the unit test failures.

Ok, it works now.

**Review by leyao-daily — APPROVED** [review]
LGTM. Thanks. It seems that in this situation, we need a dummy server to run the whole workload?

**Review by Hulongyin — APPROVED** [review]
LGTM. Thanks. And we may also need to update Dockerfile and helm to run the whole workload.

**Pull request merged**
