### PR TITLE
README.md: Add a Note in README

### PR DESCRIPTION
**Pull request by hwang37**
A Note of non-production disclaimer.

### CODE REVIEW

**Review by Hulongyin — COMMENTED** [review]
Hi, @hwang37 you can merge two commits in this PR into one, and modify the commit message, prefixed with `README.md:`, the same format as PR title, and the subject line should be no longer than 72 characters, refer to https://github.com/intel/cloud-native-ai-pipeline/blob/main/CONTRIBUTING.md#subject-line-format

**Comment by leyao-daily** [comment]
Please clean the unnecessary commit.

**Review by Hulongyin — APPROVED** [review]
LGTM. Thanks

**Comment by hwang37** [comment]
@leyao-daily @Hulongyin Thanks for review. Cleanup the commit done.

**Pull request merged**
